### ISSUE TITLE
[User Management] Roles Management

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#10]
### Problem Description

Currently, we rely on premade roles provided by Omni to manage permissions. While this is a great temporary fix, we'd like to have the flexibility to manage our own roles and assign them to people w/ access to Omni. 

### Solution

In User Management, we'd like to:
- Define Roles and the permissions associated w/ each
- Assign Roles to Users
- Permissions to Define and Assign roles are given to admins (or anyone w/ permissions to CRUD users)

### Alternative Solutions

Haven't really considered alternatives and honestly can't think of any. We *could* go through and customize every role to 'custom' but that's not really viable.

**Comment by smira** [comment]
This will come in the form of the ACL policy in the future release of Omni.

**Comment by smira** [comment]
Please see [ACL docs](https://omni.siderolabs.com/docs/how-to-guides/how-to-manage-acls/).
