### ISSUE TITLE
Cluster tagging

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#16]
### Problem Description

We'd like to be able to use tags at the cluster level. One challenge we have right now is that clusters are prepped at headquarters before they are then packed up and shipped out. It’s difficult for us to discern between a cluster that is supposed to be offline vs one that is not.
We’d love to be able to tag a cluster (like we can with machines) to indicate that it’s in certain expected phases (e.g. pre-shipment)

### Solution

Be able to use tags at the cluster level.

**Comment by smira** [comment]
This will be released in Omni 0.9.0
