### ISSUE TITLE
[bug] Cannot delete machine label from UI

### ISSUE THREAD

**Issue by gerhard** [siderolabs/omni-feedback#18]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have created an incorrect label for a machine. I cannot delete it. I cannot update it either. 

### Expected Behavior

I would expect to be able to delete labels assigned to machines.

### Steps To Reproduce

Notice the `u-created:2011` label. Clicking on `x` does not delete it.

Notice the `labels` payload in the `POST https://changelog.omni.siderolabs.io/api/omni.resources.ResourceService/Update` request.

![image](https://user-images.githubusercontent.com/3342/230922272-478197ff-2937-40d3-8e16-3920a0f80dfa.png)

### What browsers are you seeing the problem on?

Chrome

**Comment by smira** [comment]
Thanks for reporting this issue.

We have a fix for this issue already in the development version of Omni. If we don't do a hotfix earlier, the fix should come with v0.7.0 next week.

**Comment by gerhard** [comment]
Thank you for the super prompt response! I will keep an eye on this.

I'm really excited to be finally resuming https://shipit.show/84. BTW, the machine in the screenshot above is the same one next to @steverfrancis & @andrewrynhard in that podcast picture.

---

FWIW, I have a few more like this one coming in shortly. Some are for OSS Talos. I intend to post these in https://github.com/siderolabs/talos/discussions, instead of Slack. I prefer to have a public link that I can keep for future reference, cross-link between repositories & and a slower discussion. I never liked the fire & forget Slack. Hope that's OK.

**Comment by gerhard** [comment]
Checking whether this will be released in Omni v0.7.0+ too - re https://github.com/siderolabs/omni-feedback/issues/19#issuecomment-1505043867

**Comment by smira** [comment]
yes, both will be released with Omni v0.7.0

**Comment by gerhard** [comment]
Works as expected. Thank you!

![image](https://user-images.githubusercontent.com/3342/232900086-0327daa6-c415-4d8e-9156-1f3df0023eba.png)
