### ISSUE TITLE
[bug] Different net label values for machines with 1Gbps uplinks

### ISSUE THREAD

**Issue by gerhard** [siderolabs/omni-feedback#19]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Two machines have a 1Gbps uplink. One is auto-labelled with `net: 1Gbps`. The other one is auto-labelled with `net: 1000Mbps`. Filtering for machines with `1Gbps` networking now produces incorrect results. See the screenshots attached.

---

By the way, there is similar behaviour for the `cpu` label. One is reporting as `intel`, while the other is reporting as `intel(r) corporation`. Both machines are bare metal with genuine Intel CPUs:
- `smpboot: CPU0: Intel(R) Xeon(R) CPU E31230 @ 3.20GHz (family: 0x6, model: 0x2a, stepping: 0x7)`
- `smpboot: CPU0: Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (family: 0x6, model: 0x3c, stepping: 0x3)`

### Expected Behavior

Both machines should be auto-labelled as either `1Gbps` or `1000Mbps`. My preference would be 1Gbps.

### Steps To Reproduce

1. Boot two different machines with 1Gbps networking running Talos OS (from Omni).
2. There is a good chance that one will label itself with `1Gbps`, while the other one will report as `1000Mbps`

### Anything else?

![image](https://user-images.githubusercontent.com/3342/230937512-2c30545a-8a41-44cc-9b97-b6cffa6777bf.png)

![image](https://user-images.githubusercontent.com/3342/230937681-dbb2b037-88a3-49d7-b457-c0728168793e.png)

![image](https://user-images.githubusercontent.com/3342/230937768-b4e6b599-9cfd-46e2-b1e1-5977e4100a4b.png)

**Comment by smira** [comment]
I guess network speed is a bug in hardware SMBIOS info, one has 1000Mbps, another 1024Gbps. 

But anyways we should fix it.

**Comment by gerhard** [comment]
Both machines report `1000Mbps`:

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/3342/230957681-b268c25e-2aa3-4c5a-8ba4-33e71740856c.png">

**Comment by smira** [comment]
I talk about SMBIOS info, `dmidecode` on Linux.

**Comment by gerhard** [comment]
Is there a way to check that with Talos?

Maybe `omnictl machine-logs <MACHINE-ID>` is not the right command.

**Comment by smira** [comment]
we will fix it on Omni side, it should be visible in `omnictl get machinestatus -o yaml` output

**Comment by gerhard** [comment]
Got it, thanks!

BTW, `omnictl get resourcedefinition` is super useful.

**Comment by smira** [comment]
The fix will be released with Omni v0.7.0+

**Comment by gerhard** [comment]
`net` now works as expected. Same for `cpu`. Thank you!

![image](https://user-images.githubusercontent.com/3342/232900283-a485128b-1b70-474d-8182-4b537fbf6681.png)
