### ISSUE TITLE
[feature] Custom cluster endpoint

### ISSUE THREAD

**Issue by mcflis** [siderolabs/omni-feedback#22]
### Problem Description

When I try to create a cluster and override the `cluster.controlPlane.endpoint` an error occurs:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/19263910/231369654-c30f2c77-7d5a-48c1-a881-08c1777a2c46.png">

I couldn't find a form input to set the controlplane endpoint.\
However, to me it seems to be useful for local-only clusters (i.e., in a homelab) especially when the internet connection drops due to an ISP issue or so.

### Solution

Allow to customise the endpoint for a local-only (or if feasible for any) cluster.

### Notes

The [VIP](https://www.talos.dev/v1.3/talos-guides/network/vip/) feature of talos seems to be useless when using Omni

**Comment by Unix4ever** [comment]
Hello,

The reason for not allowing overriding the `endpoint` is that Omni creates loadbalancer for each cluster it manages.
So it automatically sets up `endpoint` to be loadbalancer IP in the internal wireguard network.

I agree that nothing stops us from creating a cluster without loadbalancer though.
I don't think we have a clear solution planned for that so far.

I will create an issue to discuss that.

**Comment by mcflis** [comment]
Ok I see, so currently, there is no temporary offline mode with omni, i.e., the cluster cannot operate when the omni endpoint is not reachable, correct? 

Can Talos/K8s still handle http requests (ingress) while the control plane is not reachable?

To me personally, temporary offline mode is mission critical since I can't afford my services (seafile, home assistant, etc.) not to be reachable during an internet outage.

**Comment by Unix4ever** [comment]
> Ok I see, so currently, there is no temporary offline mode with omni, i.e., the cluster cannot operate when the omni endpoint is not reachable, correct?

Correct. We have some ideas for the offline mode, but need more time to finalize the design.

> Can Talos/K8s still handle http requests (ingress) while the control plane is not reachable?

Yes, the workload should be running. Only thing which won't work is scheduling new pods.

**Comment by mcflis** [comment]
> Correct. We have some ideas for the offline mode, but need more time to finalize the design.

Very cool! Take your time.

> Yes, the workload should be running. Only thing which won't work is scheduling new pods.

This is something I can live with for the moment.


Thanks for your feedback.\
Keep up the good work!

**Comment by smira** [comment]
We are looking towards documenting this flow with Omni.

**Comment by smira** [comment]
With Talos 1.5+, Omni enables by default [KubePrism](https://www.talos.dev/v1.5/kubernetes-guides/configuration/kubeprism/) feature. This doesn't solve the issue, but in-cluster Kubernetes API traffic will be local now.

**Comment by mcflis** [comment]
Nice, I haven't tried it yet, but it sounds like it would solve my use case: have the k8s control plane working when there is no internet access.

**Comment by steverfrancis** [comment]
KubePrism for the win!
