### ISSUE TITLE
[bug] Documentation for Creating Kube SA 

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://omni.siderolabs.com/docs/how-to-guides/how-to-create-kubernetes-service-account/#creating-the-service-account-kubeconfig 
isn't reflected in
https://omni.siderolabs.com/docs/reference/cli/

### Expected Behavior

https://omni.siderolabs.com/docs/how-to-guides/how-to-create-kubernetes-service-account/#creating-the-service-account-kubeconfig 
is reflected in
https://omni.siderolabs.com/docs/reference/cli/

### Steps To Reproduce

1. Check out https://omni.siderolabs.com/docs/reference/cli/
2. No reference to kube SA
3. It's referenced in https://omni.siderolabs.com/docs/how-to-guides/how-to-create-kubernetes-service-account/#creating-the-service-account-kubeconfig

**Comment by smira** [comment]
Thanks for bringing this up, CLI reference should be updated in a few second on the website.
