### ISSUE TITLE
[feature] Per Cluster Permissions for Users

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#27]
### Problem Description

We would like to have the ability to assign permissions to users on a per-cluster basis. 

### Solution

Open to solutions; preferably, able to manage this in a permissions panel of some kind to easily manage permissions all in one place.

**Comment by smira** [comment]
Should be available with the ACL policy (#10)

**Comment by smira** [comment]
Please see [ACL docs](https://omni.siderolabs.com/docs/how-to-guides/how-to-manage-acls/).
