### ISSUE TITLE
[bug] Omni not reporting correct dedicate core count

### ISSUE THREAD

**Issue by ryandellolio** [siderolabs/omni-feedback#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After creating an EC2 instance using the provided installation media and documentation, my AWS EC2 instances connected easily and quickly, however Omni is reporting the incorrect number of CPU cores.  After spinning up a few m6i.large instances with [2 dedicated cpus](https://instances.vantage.sh/aws/ec2/m6i.large), the reported CPU count is 1.  Also notable is that these are dedicated CPU cores, not shared cores or burstable instances.  I have not tested on other instance types.

This is a minor issue but:

1. could cause confusion as larger fleets are deployed on Omni.  
2. there may be future plans for further dashboarding for which this would cause problems

### Expected Behavior

Report the correct number of cores / dedicated CPUs regardless of cloud platform

### Steps To Reproduce

- Build AMI using latest installation media from dashboard and using AWS CLI per documentation
- Launch m6i.large instance using the new AMI
- Observe CPU count in AWS EC2 instance details pane
- Observe different count in Omni

### What browsers are you seeing the problem on?

Safari

### Anything else?

EC2:
<img width="184" alt="Screenshot 2023-03-02 at 4 06 12 PM" src="https://user-images.githubusercontent.com/4984020/222613599-84201bc7-ae44-4fa2-939f-e86a5acded24.png">

<img width="202" alt="Screenshot 2023-03-02 at 4 05 35 PM" src="https://user-images.githubusercontent.com/4984020/222613603-b6ae4efb-3d27-4513-a6d2-398d67b7745f.png">
Omni:

![unnamed](https://user-images.githubusercontent.com/4984020/222613600-97b8b202-fb81-4c6b-9887-951c045aafa9.png)

**Comment by smira** [comment]
Number of `vCPUs` might not match the information showed, as `vCPU` is not a core, and there might be e.g. Hyper Threading. 

Omni shows what the VM reports in the hardware information. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-optimize-cpu.html
