### ISSUE TITLE
[feature] ArgoCD over existing Wireguard 

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#32]
### Problem Description

There is a UI in omni that we can't give developers access to. It would be great Omni could have a plugin to view ArgoCD within Omni.

**Comment by smira** [comment]
Note: this might be a more generic feature - exposing generic private http:// endpoint via Omni with TLS termination and auth integrated. @andrewrynhard need your feedback

**Comment by ArcherSeven** [comment]
We'd loved that solution.

**Comment by smira** [comment]
It's coming in some of the next releases of Omni.

**Comment by utkuozdemir** [comment]
We have developed a feature which would allow this: https://omni.siderolabs.com/docs/how-to-guides/how-to-expose-http-service-from-a-cluster/

Closing this issue as completed. Feel free to share any new feedback on this feature.
