### ISSUE TITLE
[feature] Show last seen time for machines

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni-feedback#4]
### Problem Description

In the Machines view in Omni, I want to be able to see when an offline machine was last connected, and be able to sort the machine list by how long since last seen.

### Notes

https://taloscommunity.slack.com/archives/C03MB6ASQ6S/p1677864240763279

**Comment by smira** [comment]
Coming in Omni 0.8.0

**Comment by ArcherSeven** [comment]
Confirmed!  Ty!
