### ISSUE TITLE
[feature] Need unauthenticated source for omnictl or omnictl compatibility with older versions of omni

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni-feedback#44]
### Problem Description

I need to be able to download or include an `omnictl` in an image that will work across our environments, even when those environments are on different versions of omni, without having to authenticate first, or using a non-interactive authentication method.

**Comment by smira** [comment]
`omnictl` download is unauthenticated:

```
curl -LO https://<instance>.omni.siderolabs.io/omnictl/omnictl-linux-amd64
```

(other platforms/architectures also available)

Omni client code is open-source for building higher-level automation: https://github.com/siderolabs/omni-client
