### ISSUE TITLE
[bug] Failed to Confirm authenticate request

### ISSUE THREAD

**Issue by YazidPF** [siderolabs/omni-feedback#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click grant access to Authenticate Kubernetes Access leads to the error:
Failed to confirm authenticate request
Invalid Signature

### Expected Behavior

To log in, grant access. This allows me to see pods

### Steps To Reproduce

1. In VScode: kubectl get pod 
2. Please visit the following URL in your browser manually: http://localhost:8000 <- Click link to prompt access.
3. Log in with github
4. Click grant access. 

### What browsers are you seeing the problem on?

Chrome

### Anything else?

<img width="1901" alt="Error Signature" src="https://github.com/siderolabs/omni-feedback/assets/107963072/e40c1c69-9609-4419-8462-16c960179d37">

**Comment by smira** [comment]
Might be same as #50
