### ISSUE TITLE
[feature] Sort by hostname in machine overview

### ISSUE THREAD

**Issue by netthier** [siderolabs/omni-feedback#48]
### Problem Description

Currently, the machine overview allows sorting by creation time, machine id and last active time.
All my nodes get their hostnames via DHCP and are named like \<cluster>-00, \<cluster>-01, etc.
However, because they were all added at different times, nodes from various clusters appear in a random order in the machine overview.

### Solution

I'd like to be able to sort alphabetically by hostname, so that all machines belonging to the same cluster are grouped together and I can quickly find specific nodes by their index (the number in the hostname).

### Alternative Solutions

/

**Comment by Unix4ever** [comment]
Fixed in v0.13.0
