### ISSUE TITLE
[bug] Failed to Fetch 

### ISSUE THREAD

**Issue by zgomez301** [siderolabs/omni-feedback#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Constant failed to fetch and failed posts in console log
browser.js:95     POST https://powerflex.omni.siderolabs.io/api/omni.resources.ResourceService/Watch 401

Seems to be present 80+% of the time using omni

Cleared cache/cookies/multiple browsers/icognito

### Expected Behavior

Ability to use omni

### Steps To Reproduce

Log in to any browser

### Anything else?

![image](https://github.com/siderolabs/omni-feedback/assets/70731147/d2adc6a1-e91b-4768-b78f-82a5d4f18d26)

**Comment by smira** [comment]
This issue was fixed, it was caused by time sync issues.
