### ISSUE TITLE
[bug] can't login - failed to confirm public key

### ISSUE THREAD

**Issue by uhthomas** [siderolabs/omni-feedback#5]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/9749173/224180260-a830b840-a12a-45d8-9945-2c9af4a3c57b.png)

### Expected Behavior

I should be able to login.

### Steps To Reproduce

?

### What browsers are you seeing the problem on?

Chrome

### Anything else?

I'm using a Google account if that helps.

**Comment by smira** [comment]
This means that the email you're authenticating with doesn't match any of the authorized users for this instance of Omni.

**Comment by uhthomas** [comment]
I see - that makes sense.

The email I entered is an alias for the actual email on the account. I guess I should reach out to support to fix that? Alternatively I guess I could try logging in with GitHub.

**Comment by smira** [comment]
Now Omni has a better message for this case.
