### ISSUE TITLE
[bug] No machine details showing in "Machines" list

### ISSUE THREAD

**Issue by gtaylor** [siderolabs/omni-feedback#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

None of my newly registered Machines are showing any details. IP addresses, Talos versions, memory, disk. This is on the "aegn" Omni account.

![image](https://github.com/siderolabs/omni-feedback/assets/75556/77ad4206-e853-44d5-8456-2094a14902bb)

### Expected Behavior

I expect to see the details for each of my registered but unassigned machines.

### Steps To Reproduce

1. In the "aegn" Omni account, register a new machine.
2. Navigate to the Machines page.
3. Note the absence of machine details for registered machines.

### What browsers are you seeing the problem on?

Chrome

**Comment by smira** [comment]
was this machine running Talos previously? not being wiped and still running Talos on being joined?

**Comment by gtaylor** [comment]
Looks like a delete + a wipe via PXE + a reinstall fixed this.
