### ISSUE TITLE
[bug] "Download Installation Media" downloads out of date ISO

### ISSUE THREAD

**Issue by gtaylor** [siderolabs/omni-feedback#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Talos Linux was released on June 28. I am attempting to download a customized ISO to auto-join my Omni account:
```
$ omnictl download iso --arch amd64 
Downloading talos-amd64-v1.4.5-omni-aegn.iso to /home/myuser/Downloads/talos-amd64-v1.4.5-omni-aegn.iso
Downloaded talos-amd64-v1.4.5-omni-aegn.iso to /home/myuser/Downloads/talos-amd64-v1.4.5-omni-aegn.iso
```
Notice that 1.4.5 is downloaded.

### Expected Behavior

Since 1.4.6 is the latest stable version of Talos, I'd expect 1.4.6 to be downloaded instead of 1.4.5.

### Steps To Reproduce

Either of the two paths to downloading customized media will reproduce the issue:

Run:
```
omnictl download iso --arch amd64
```

OR click on the "Download Installation Media" button in the Omni web ui.

### What browsers are you seeing the problem on?

Chrome

**Comment by smira** [comment]
Omni will default to Talos 1.4.6 in the next release 0.13.0 this week

**Comment by smira** [comment]
Either way, this doesn't block the creation of the cluster, as Omni will upgrade the node automatically behind the scenes
