### ISSUE TITLE
[bug] New Account "You don't have access to Omni Web"

### ISSUE THREAD

**Issue by mthird** [siderolabs/omni-feedback#52]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Authorization error when logging in for new trial:

![image](https://github.com/siderolabs/omni-feedback/assets/537988/7d0701fe-f123-47f9-ad8c-978feb77b405)

### Expected Behavior

Access to the trial

### Steps To Reproduce

1. Sign up for the trial
2. Wait for email link
3. Click link
4. Sign in using Google or GitHub (I tried both)

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by andrewrynhard** [comment]
Hi @mthird . Does this go away with a page refresh?

**Comment by mthird** [comment]
> Hi @mthird . Does this go away with a page refresh?

No, it doesn't.

**Comment by TimJones** [comment]
Hi @mthird, in the logs I can see your initial login attempt and it failed due to a key expiry.

Can you ensure your system clock is synced and not off by more than a few minutes?

**Comment by TimJones** [comment]
Also, if you need to update your system clock, then you will need to clear the browser cache for Omni before attempting to log in again.

**Comment by mthird** [comment]
My system clock is synced correctly.   I tried clearing cookies/session storage and logging in again but to no avail.

**Comment by andrewrynhard** [comment]
Hi @mthird. We are looking into this now. Are you on our Slack?

**Comment by mthird** [comment]
on it now ...
