### ISSUE TITLE
[bug] Omni displays incorrect resource requests for CPU and Memory on its dashboard

### ISSUE THREAD

**Issue by ArcherSeven** [siderolabs/omni-feedback#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Our Dashboards indicate that are resource requests for memory and CPU are substantially higher than they actually are.

### Expected Behavior

Dashboard should reflect reality.

### Steps To Reproduce

In production, open any cluster in the web UI, look at the dashboard.  Compare to `kubectl describe node` for the same cluster.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by smira** [comment]
Dup of https://github.com/siderolabs/omni/issues/192
