### ISSUE TITLE
[bug] Error: failed to create containerd task for nvidia-device-plugin

### ISSUE THREAD

**Issue by sjdrc** [siderolabs/omni-feedback#6]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I followed the Nvidia OSS guide https://www.talos.dev/v1.3/talos-guides/configuration/nvidia-gpu/ to setup a host, and after installing the device plugin helm chart, the nvidia-device-plugin pod is stuck in a CrashLoop with the following error:

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: detection error: nvml error: not found: unknown
```

### Expected Behavior

Gpu operator works after following the instructions.

### Steps To Reproduce

Follow the Nvidia GPU OSS guide

**Comment by sjdrc** [comment]
The issue is:
```
15/03/2023
14:20:40
NVRM: Open nvidia.ko is only ready for use on Data Center GPUs.
15/03/2023
14:20:40
NVRM: To force use of Open nvidia.ko on other GPUs, see the
15/03/2023
14:20:40
NVRM: 'OpenRmEnableUnsupportedGpus' kernel module parameter described
15/03/2023
14:20:41
NVRM: in the README.
15/03/2023
14:20:41
NVRM: GPU 0000:1a:00.0: RmInitAdapter failed! (0x63:0x0:1905)
15/03/2023
14:20:41
NVRM: GPU 0000:1a:00.0: rm_init_adapter failed, device minor number 0 
```

In the logs.

The fix is: https://github.com/siderolabs/talos/pull/6209

I have edited the config patches and rebooted the node but the config has not updated. Am I forgetting something here?

**Comment by frezbo** [comment]
what does `talosctl read /proc/modules/nvidia/parameters` return? (I think this is the path based on memory, or you could do `taloscl ls /proc/modules` and look it up?)

**Comment by sjdrc** [comment]
I've since destroyed this cluster, but when I went to the node config page from the cluster and looked at the generated config, the updates from the config patches were not in there.
