### ISSUE TITLE
[bug] Digital Ocean installation media not downloading

### ISSUE THREAD

**Issue by roeeklinger** [siderolabs/omni-feedback#60]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you try to download the Digital Ocean installation media from the Omni web UI, it downloads a file that is 0 Bytes.

### Expected Behavior

The Digital Ocean Omni installation media should be properly downloaded.

### Steps To Reproduce

Go into the Omni web UI and try to download the Omni installation media.

### What browsers are you seeing the problem on?

Chrome, Safari

**Comment by smira** [comment]
From `#omni` channel in Slack:

The "download installation media" feature of Omni is broken in the current version (v0.16.0) for any non-ISO assets. It's a non-trivial fix and we want to get it right, so it'll probably get rolled out on Monday of next week. In the meantime, if you need to generate media and you're down to experiment a bit, you can try our imager container directly. Here's some examples:

```
# Raspberry Pi

docker run -it -v /dev:/dev -v $PWD:/out --privileged ghcr.io/siderolabs/imager:v1.5.1 rpi_generic --arch arm64 --extra-kernel-arg='<parameters from the "Copy Kernel Parameters" button in omni>'

# Cloud Images (Update the first imager arg with your cloud of choice)

docker run -it -v /dev:/dev -v $PWD:/out --privileged ghcr.io/siderolabs/imager:v1.5.1 <aws,azure,digital-ocean,gcp,etc.> --extra-kernel-arg='<parameters from the "Copy Kernel Parameters" button in omni>'
```

You can also see [here](https://www.talos.dev/v1.5/talos-guides/install/boot-assets/) for lots of details on imager.

**Comment by smira** [comment]
It should be fixed now
