### ISSUE TITLE
[bug] talosctl commands fail with "error reading server preface: remote error: tls: bad certificate"

### ISSUE THREAD

**Issue by gerhard** [siderolabs/omni-feedback#64]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All `talosctl` commands fail with:

```cfg
error fetching time: rpc error: code = Unavailable desc = last connection error: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
```

This is the last one that I ran:

```cfg
talosctl-1.5.3 time -n h12-london
error fetching time: rpc error: code = Unavailable desc = last connection error: connection error: desc = "error reading server preface: remote error: tls: bad certificate"
```

### Expected Behavior

I would expect `talosctl` v1.5.3 to be able to communicate with this node running Talos OS v1.5.3.

### Steps To Reproduce

macOS 12.6.9 Intel running `talosctl` v1.5.3:

```cfg
talosctl-1.5.3 version
Client:
	Tag:         v1.5.3
	SHA:         cb21c671
	Built:
	Go version:  go1.20.8
	OS/Arch:     darwin/amd64
```

**Comment by smira** [comment]
Probably using wrong `talosconfig` (not from Omni).

**Comment by gerhard** [comment]
This looks the right `$TALOSCONFIG` to me:

<img width="844" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/3342/4a343076-1c2e-4fdd-8d64-7bdc3885fd1c">

**Comment by smira** [comment]
I don't see the identity part, but it feels like Omni is using wrong cert (?). Do you have anything like this cluster was re-created with the same name? Trying to guess here.

**Comment by gerhard** [comment]
I was only showing the first 5 lines, the rest of that `$TALOSCONFIG` is exactly as downloaded from Omni.

Each cluster has a unique name, it gets a new name when it's re-created.

I deleted all of `~/Library/Application Support/talos`, and still getting the same error.

How can I debug this further?

**Comment by smira** [comment]
I will take a look at the server side logs, do you have a cluster name to help me to find it?

**Comment by smira** [comment]
I restarted your instance, please let me know if it clears the error, but we'll still be looking for an actual error

**Comment by gerhard** [comment]
That worked!

<img width="1435" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/3342/d1219565-1f59-462c-a4d0-a50fe6003f66">

While a bunch of things are not showing as they should on the dashboard, at least `omnictl` is now working as expected.

Thank you!
