### ISSUE TITLE
[bug] Error when destroying a node

### ISSUE THREAD

**Issue by sjdrc** [siderolabs/omni-feedback#7]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error appears when destroying a node from a cluster:

> Failed to Destroy The Node
> can't access property "metadata", a[h] is undefined

I've currently got this with 2 different nodes.

### Expected Behavior

The node is removed from the cluster

### Steps To Reproduce

1. Select a cluster
2. Select node in the cluster
3. Click Destroy

**Comment by smira** [comment]
Can you please provide some more information on the issue? is it a control plane or worker node? how many nodes does the cluster have?

**Comment by sjdrc** [comment]
This was a cluster with 3 control nodes and 5 workers. I was trying to delete a worker.

I was unable to move forwards with this so I deleted the cluster.

**Comment by steverfrancis** [comment]
Any chance that the machines had duplicate node names?

**Comment by smira** [comment]
This should be fixed by now, please feel to re-open if the issue persists.
