### ISSUE TITLE
[feature] Make Omni changelog public

### ISSUE THREAD

**Issue by steverfrancis** [siderolabs/omni-feedback#70]
### Problem Description

We have release notes for each Omni release, but they are in a private repo.
Users want to see what is changing with each Omni update.

### Solution

We need to mirror the releasenotes from e.g. https://github.com/siderolabs/omni/releases/tag/v0.25.0 to the Omni docs site.

**Comment by Unix4ever** [comment]
Or we can show it in the app itself.
