### ISSUE TITLE
[feature] Homebrew tap for omnictl

### ISSUE THREAD

**Issue by jdmcmahan** [siderolabs/omni-feedback#75]
### Problem Description

It would be nice to manage `omnictl` installations via Homebrew like we can with [`talosctl`](https://github.com/siderolabs/homebrew-talos). This would simplify installation and upgrades especially for users who rely heavily on cluster templates.

Some of the solutions proposed here might also help with general availability of `omnictl` for [containerized tooling](https://github.com/ryandellolio/alpine-k8s-omni), etc.

### Solution

Ideally, the `omnictl` binaries would be published as a release under https://github.com/siderolabs/omni-client. This would make it trivial to include the binaries in a Homebrew tap a la https://github.com/siderolabs/homebrew-talos.

Currently there are no releases for that repository, and versions newer than `0.11.1` are not tagged.

### Alternative Solutions

Looking at the Talos structure, I'm assuming all Omni releases are maintained under a (understandably) closed-source upstream monorepo. Instead of duplicating the `omnictl` release across repos, a [GitHubPrivateRepositoryReleaseDownloadStrategy](https://github.com/goreleaser/goreleaser/issues/507) could be used in a theoretical `homebrew-omni` tap to fetch the binaries from the private Omni repository. This would require help from the Omni team to set up an access token along with the tap.

### Notes

I did notice the `omnictl` binaries are available without authentication from my personal subdomain at `*.omni.siderolabs.io/omnictl`. However, I'd prefer to not build integrations around these for the following reasons:
- downloading from a particular Omni subdomain is not conducive to sharing
- triggering an update upon release of a new version would still be a challenge

**Comment by andrewrynhard** [comment]
I like this idea. We recently are looking at revamping our Talos docs to use Brew.

@Unix4ever Is `omnictl` open source?

CC @rothgar

**Comment by jdmcmahan** [comment]
Closing per https://github.com/siderolabs/homebrew-tap/pull/60.
