### ISSUE TITLE
[feature] Omni (Sidero) Terraform Provider

### ISSUE THREAD

**Issue by rmvangun** [siderolabs/omni-feedback#76]
### Problem Description

As with everything else, it would be great to declaratively configure Omni with Terraform! 

### Solution

Because there's already a Talos provider, it seems you'd put them both under a common Sidero provider with combined `sidero_talos_` and `sidero_omni_` resources.

**Comment by steverfrancis** [comment]
Tracked in https://github.com/siderolabs/omni/issues/53
