### ISSUE TITLE
[bug] Issues with managing and reporting machines

### ISSUE THREAD

**Issue by krobertson** [siderolabs/omni-feedback#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am having 2 sets of issues with machines:

First, I had created some machines and was working with them. I destroyed the clusters, deleted the machines in Omni, wipe/reset the machines, booted fresh on PXE, and one of the nodes was up and in maintenance mode, but not showing in the UI at all.

However, with some investigating, I found that it is shown on the cluster creation page, and is shown with `omnictl`. However, I cannot delete it with `omnictl`, since it says permission denied.

### Machine List
<img width="877" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/1809/afbd694f-ab2a-43af-b282-981a25ddb269">

### Cluster Creation
<img width="919" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/1809/1b36aee9-324d-4b2e-a852-cb99a3ac343a">

### omnictl output and deletion
<img width="955" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/1809/1371a9ed-78a7-4b53-ba20-7644bef6059f">

Mystery stuck machine is `b06c08f0-a27a-24f5-deaf-f02f741ab0a6`.

Second, since I decided to start over with the machines, none of the other machines have been showing any metadata in the UI or over CLI, so I can't apply any machine classes based on hardware, and creating a new cluster does not pre-select the installation disk at all. These are on new machines that I've spun up with Proxmox. I have deployed to them with a config patch to select a disk. I've tried wiping them, I've tried creating brand new VMs, I've even tried both PXE booting and ISO booting. I had seen #50, however wiping did nothing, and even on a new machine with no install, there is nothing to wipe.

<img width="1197" alt="image" src="https://github.com/siderolabs/omni-feedback/assets/1809/f06048d9-c50a-49e5-8165-a160e363ab8e">

### Expected Behavior

Be able to see all the machines, be able to remove machines, and be able to see machine metadata.

### Steps To Reproduce

1. Create new VM
2. Wait for it to boot
3. Machine shows in Omni, but with no metadata

### What browsers are you seeing the problem on?

Chrome

**Comment by Unix4ever** [comment]
It's actually:
`omnictl delete link b06c08f0-a27a-24f5-deaf-f02f741ab0a6`

To remove the machine from Omni.

**Comment by krobertson** [comment]
@Unix4ever Thanks. Deleting the link cleared up the issue with the stuck machine.

**Comment by steverfrancis** [comment]
This should be fully resolved (so you cant get in this state) with the recent release of Omni
