### ISSUE TITLE
[feature] Manage Node Extensions via Web UI

### ISSUE THREAD

**Issue by jahanson** [siderolabs/omni-feedback#81]
### Problem Description

Right now it takes a lot more effort than it should to change out extensions from nodes. I used to be able to change the machine config or just install an ISO on a new node in maintenance mode. I'd like to see a feature that makes it as easy to manage the current extensions on a node as it is to build an image from https://factory.talos.dev.

### Solution

![image](https://github.com/siderolabs/omni-feedback/assets/1548511/3daf5984-e82b-4c14-9e36-06397a2de054)
This is all you need to manage extensions on a node but instead of "Download" have it say "Apply"?

**Comment by steverfrancis** [comment]
Done https://github.com/siderolabs/omni/issues/201
