### ISSUE TITLE
[User Management] New Users & Kubeconfig Config 

### ISSUE THREAD

**Issue by croarkpf** [siderolabs/omni-feedback#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Definitely found a bug in user management, not sure if it's front end only yet or not... testing... but when adding a new user, if I give them "read" and "update" cluster permissions, the UI only shows "update", and they cannot pull the kubeconfig.  If I give them "read" "update" and "create", it only shows "create".

### Expected Behavior

A) would be super nice if we could give read-only kubeconfigs to read-only users.  Like... super nice.
B) If I give them Create, Read, and Update, it should show that they have all three.
C) I don't understand why they seem to need Delete to be able to pull a kubeconfig... though I guess they could destroy a cluster using just kubectl, they can also do that with only "update" access.

### Steps To Reproduce

1. Go to Omni
2. Select Users
3. Edit permissions of users

### What browsers are you seeing the problem on?

Chrome

**Comment by croarkpf** [comment]
A) https://github.com/siderolabs/omni-feedback/issues/12

**Comment by smira** [comment]
> Definitely found a bug in user management, not sure if it's front end only yet or not... testing... but when adding a new user, if I give them "read" and "update" cluster permissions, the UI only shows "update", and they cannot pull the kubeconfig. If I give them "read" "update" and "create", it only shows "create".

This was fixed in Omni 0.8.0

**Comment by smira** [comment]
Kubeconfig permissions can be controlled in fine-grained manner via ACLs: https://omni.siderolabs.com/docs/how-to-guides/how-to-manage-acls/
